# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
name: create-release-from-semver-tag

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release from semver tag
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
